name: tensorflow_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - matplotlib
  - pandas
  - pip
  - tensorflow
  - pip:
    - opencv-python
    - keras